// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RoyalCourtWebapp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230111215135_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("RoyalCourtWebapp.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Appearance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CourtId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Extrovertness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Honor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sexuality")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("CourtId");

                    b.HasIndex("HouseId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MonarchCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PalaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourtId");

                    b.HasIndex("MonarchCharacterId");

                    b.HasIndex("PalaceId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("RoyalCourtWebapp.DailyEvent", b =>
                {
                    b.Property<int>("DailyEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DailyEventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DailyEventId");

                    b.ToTable("DailyEvents");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Holdings", b =>
                {
                    b.Property<int>("HoldingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoldingsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HoldingsId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("RoyalCourtWebapp.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyHonor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HouseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Interaction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractionHolder1CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InteractionHolder2CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InteractionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InteractionId");

                    b.HasIndex("InteractionHolder1CharacterId");

                    b.HasIndex("InteractionHolder2CharacterId");

                    b.ToTable("Interaction");
                });

            modelBuilder.Entity("RoyalCourtWebapp.MemoryRC", b =>
                {
                    b.Property<int>("MemoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectedInteractionInteractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MemoryId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConnectedInteractionInteractionId");

                    b.ToTable("MemoryRC");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Opinion", b =>
                {
                    b.Property<int>("OpinionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpinionHolderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpinionOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpinionValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("OpinionId");

                    b.HasIndex("OpinionHolderCharacterId");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Palace", b =>
                {
                    b.Property<int>("PalaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PalaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PalaceId");

                    b.ToTable("Palaces");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PalaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.HasIndex("PalaceId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HoldingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TitleId");

                    b.HasIndex("HoldingsId");

                    b.HasIndex("OwnerCharacterId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("RoyalCourtWebapp.WeeklyEvent", b =>
                {
                    b.Property<int>("WeeklyEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeeklyEventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WeeklyEventId");

                    b.ToTable("WeeklyEvents");
                });

            modelBuilder.Entity("RoyalCourtWebapp.YearlyEvent", b =>
                {
                    b.Property<int>("YearlyEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearlyEventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("YearlyEventId");

                    b.ToTable("YearlyEvents");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Character", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Court", null)
                        .WithMany("Subjects")
                        .HasForeignKey("CourtId");

                    b.HasOne("RoyalCourtWebapp.House", "House")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("HouseId");

                    b.Navigation("House");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Court", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Character", "Monarch")
                        .WithMany()
                        .HasForeignKey("MonarchCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoyalCourtWebapp.Palace", "Palace")
                        .WithMany()
                        .HasForeignKey("PalaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monarch");

                    b.Navigation("Palace");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Interaction", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Character", "InteractionHolder1")
                        .WithMany()
                        .HasForeignKey("InteractionHolder1CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoyalCourtWebapp.Character", "InteractionHolder2")
                        .WithMany()
                        .HasForeignKey("InteractionHolder2CharacterId");

                    b.Navigation("InteractionHolder1");

                    b.Navigation("InteractionHolder2");
                });

            modelBuilder.Entity("RoyalCourtWebapp.MemoryRC", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Character", null)
                        .WithMany("Memories")
                        .HasForeignKey("CharacterId");

                    b.HasOne("RoyalCourtWebapp.Interaction", "ConnectedInteraction")
                        .WithMany()
                        .HasForeignKey("ConnectedInteractionInteractionId");

                    b.Navigation("ConnectedInteraction");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Opinion", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Character", "OpinionHolder")
                        .WithMany("Opinions")
                        .HasForeignKey("OpinionHolderCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpinionHolder");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Room", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Palace", null)
                        .WithMany("Rooms")
                        .HasForeignKey("PalaceId");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Title", b =>
                {
                    b.HasOne("RoyalCourtWebapp.Holdings", "Holdings")
                        .WithMany()
                        .HasForeignKey("HoldingsId");

                    b.HasOne("RoyalCourtWebapp.Character", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerCharacterId");

                    b.Navigation("Holdings");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Character", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Court", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("RoyalCourtWebapp.House", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("RoyalCourtWebapp.Palace", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
